GET http://localhost:8000/api/v1/user?page=1&size=2

### hello
POST http://localhost:8000/api/v1/auth/login
Content-Type: "application/json"

{
    "emailorusername": "neeswebservices@gmail.com",
    "password": "adsf"
}