version: '3.8'
services:
    client:
        container_name: client
        image: clientimage:v1
        build:
            context: ./client
            dockerfile: react.Dockerfile
        volumes:
            - .:/client
            - /client/node_modules
        ports:
            - 3000:3000
        environment:
            - WATCHPACK_POLLING=true
        depends_on:
            - api
        networks:
            - internalnet

    api:
        container_name: api
        image: apiimage:v1
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - .:/api
            - /api/node_modules
        ports:
            - 8000:8000
        environment:
            - PORT=8000
            - MONGO_INITDB_ROOT_USERNAME=nees
            - MONGO_INITDB_ROOT_PASSWORD=nees
        depends_on:
            - mongo
        networks:
            - internalnet

    mongo:
        container_name: mongo
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=nees
            - MONGO_INITDB_ROOT_PASSWORD=nees
        ports:
            - 27017:27017
        volumes:
            - mongoDB:/data/db
        restart: unless-stopped
        networks:
            - internalnet
volumes:
    mongoDB: # Making the volume accessible by other containers

networks:
    internalnet:
        driver: bridge
