version: '3.8'
services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: react.Dockerfile
        volumes:
            - ./client:/client
            - /client/node_modules
        ports:
            - 3000:3000
        environment:
            - WATCHPACK_POLLING=true
        depends_on:
            - server

    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - .:/server
            - /server/node_modules
        ports:
            - 8000:8000
        environment:
            - PORT=8000
            - MONGO_INITDB_ROOT_USERNAME=nees
            - MONGO_INITDB_ROOT_PASSWORD=nees
        depends_on:
            - mongo

    mongo:
        container_name: mongo
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=nees
            - MONGO_INITDB_ROOT_PASSWORD=nees
        ports:
            - 27017:27017
        volumes:
            - mongoDB:/data/db
        restart: unless-stopped

volumes:
    mongoDB: # Making the volume accessible by other containers
